"""ComfyUI-Z-Image-Prompt-Builder entry point."""

from .nodes import (
    NODE_CLASS_MAPPINGS as CORE_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as CORE_NODE_DISPLAY_NAME_MAPPINGS,
)
from .modular_nodes import (
    NODE_CLASS_MAPPINGS as MODULAR_NODE_CLASS_MAPPINGS,
    NODE_DISPLAY_NAME_MAPPINGS as MODULAR_NODE_DISPLAY_NAME_MAPPINGS,
)

NODE_CLASS_MAPPINGS = {
    **CORE_NODE_CLASS_MAPPINGS,
    **MODULAR_NODE_CLASS_MAPPINGS,
}
NODE_DISPLAY_NAME_MAPPINGS = {
    **CORE_NODE_DISPLAY_NAME_MAPPINGS,
    **MODULAR_NODE_DISPLAY_NAME_MAPPINGS,
}

WEB_DIRECTORY = "./web/js"

__all__ = [
    "NODE_CLASS_MAPPINGS",
    "NODE_DISPLAY_NAME_MAPPINGS",
    "WEB_DIRECTORY",
]
