"""Keep browser previews synchronized with backend sizes and preset fallbacks."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import nodes as n
import resolution as r

TARGET = ROOT / "web/js/resolution_catalog.js"


def render_catalog():
    catalog = {
        "sizes": r.ASPECT_RESOLUTIONS,
        "defaults": r.RESOLUTION_DEFAULTS,
        "pixelMode": r.PIXEL_BUDGET_MODE,
        "presetAspects": {p: v["画面比例"] for p, v in n.PRESETS.items()},
        "legacyPresets": n.LEGACY_PRESET_NAMES,
        "defaultPreset": n.PRESET_OPTIONS[0],
    }
    return "// Generated by scripts/generate_resolution_catalog.py; do not edit.\nexport const RESOLUTION_CATALOG = " + json.dumps(catalog, ensure_ascii=False, indent=2) + ";\n"


if __name__ == "__main__":
    TARGET.write_text(render_catalog(), encoding="utf-8", newline="\n")
