"""Generate searchable bilingual phrases without changing output/random pools."""
import json
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))
import nodes
import modular_nodes


def build_catalog():
    fields = {}
    for field in nodes.FIELD_ORDER:
        fields[field] = [
            {"value": value, "zh": nodes.FIELD_TEXT[field].get(value, value),
             "en": nodes._english_atomic_value(field, value)}
            for value in nodes.FIELD_OPTIONS[field]
        ]
    return {"version": 1, "modules": modular_nodes.MODULE_FIELD_GROUPS, "fields": fields}


if __name__ == "__main__":
    output = ROOT / "web/js/library_catalog.js"
    output.write_text("// Generated by scripts/generate_library_catalog.py; do not edit manually.\n"
                      "export const LIBRARY_CATALOG = "
                      + json.dumps(build_catalog(), ensure_ascii=False, indent=2) + ";\n",
                      encoding="utf-8")
    print(f"Generated {output}")
